# Input and output

In [13]:
print('Hello World') # two ways of printing

Hello World


In [14]:
'Hello world'

'Hello world'

In [15]:
x = 15; y = 30 #using format

print("The value of x is {} and y is {}".format(x, y))

The value of x is 15 and y is 30


In [4]:
print("Hello {name}, {greeting}".format(name="Students", greeting="Good Evening"))

Hello Students, Good Evening


# Input

In [17]:
#input from user
x = input("Enter a name: ")
print(x)

Enter a name: SR
SR


# Python Keywords

We call reserved words in python as keywords.

They can't be used as variable name, function name or any other identifier and these key words are case sensitive.

In [7]:
#Getting Keywords in python by just importing

import keyword

print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


# Identifiers

Identifier is the name given to entities like class, functions, variables etc. in Python. It helps differentiating one entity from another.

Rules for Writing Identifiers:

1. Identifiers can be a combination of letters in lowercase (a to z) or uppercase (A to Z) or digits (0 to 9) or an underscore (_).

2. We cannot use special symbols like !, @, #, $, % etc. in our identifier.

In [18]:
#invalid declaration of variables

1variable = 10
1variable

SyntaxError: invalid syntax (<ipython-input-18-5a314fcce39c>, line 3)

In [19]:
#valid declaration
variable_1 = 10
variable_1

10

In [9]:
#keywords cannot be used as Identifiers

assert = 10

SyntaxError: invalid syntax (<ipython-input-9-019784859e76>, line 3)

# Python Comments

In Python, we use the hash (#) symbol to start writing a comment.

In [20]:
#Print Hello, world to console
print("Hello, world")

Hello, world


# Multi Line Comments

If we have comments that extend multiple lines, one way of doing it is to use hash (#) in the beginning of each line.

In [21]:
"""This is also a
perfect example of
multi-line comments"""

'This is also a\nperfect example of\nmulti-line comments'

# Python Indentation

1. Most of the programming languages like C, C++, Java use braces { } to define a block of code. Python uses indentation.

2. A code block (body of a function, loop etc.) starts with indentation and ends with the first unindented line. The amount of indentation is up to you, but it must be consistent throughout that block.

3. Generally four whitespaces are used for indentation and is preferred over tabs.

In [23]:
for i in range(15):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [27]:
if True:
    print("Machine Learning")

Machine Learning


# Data Types 

Every value in Python has a datatype. Since everything is an object in Python programming, data types are actually classes and variables are instance (object) of these classes.

# Numbers

Integers, floating point numbers and complex numbers falls under Python numbers category. They are defined as int, float and complex class in Python.

We can use the type() function to know which class a variable or a value belongs to and the isinstance() function to check if an object belongs to a particular class.

In [29]:
x = 25           #data type is implicitly set to integer
print(x,'is of type',type(x))  

25 is of type <class 'int'>


In [30]:
x = 2.5                            #data type is changed to float
print(x, " is of type", type(x))

2.5  is of type <class 'float'>


In [4]:
x = 1 + 2j                          #data type is changed to complex number
print(x, " is complex number?") 
print(isinstance(1+2j, complex))

(1+2j)  is complex number?
True


In [5]:
x = True                          #a is a boolean type
print(type(x))

<class 'bool'>


# Python Strings

    A string is a sequence of characters.

    Computers do not deal with characters, they deal with numbers (binary). Even though you may see characters on your screen, internally it is stored and manipulated as a combination of 0's and 1's.

    This conversion of character to a number is called encoding, and the reverse process is decoding. ASCII and Unicode are some of the popular encoding used.

    In Python, string is a sequence of Unicode character.

We can use single quotes or double quotes to represent strings. 

Multi-line strings can be denoted using triple quotes, ''' or """.

A string in Python consists of a series or sequence of characters - letters, numbers, and special characters. 

Strings can be indexed - often synonymously called subscripted as well. 

Similar to C, the first character of a string has the index 0.

In [32]:
s = "Hello, Welcome"
print(s)

Hello, Welcome


In [33]:
print(s[0])

H


In [34]:
#slicing
s[5:]

', Welcome'

In [40]:
string = 'Welcome'

sli_obj = string[0:7:2]

print(sli_obj)

Wloe


# String Operations

# Concatenation

Joining of two or more strings into a single one is called concatenation.

The + operator does this in Python. Simply writing two string literals together also concatenates them.

The * operator can be used to repeat the string for a given number of times.

In [41]:
s1 = "Hello "
s2 = "Welcome"

#concatenation of 2 strings
print(s1 + s2)

#repeat string n times
print(s1 * 3)

Hello Welcome
Hello Hello Hello 


# Iterating Through String

In [45]:
count = 0
for l in "Hello Welcome":
    if l == 'W':
        count += 1
print(count, ' letters found')

1  letters found


# String Methods

In [45]:
"Hello".lower()

'hello'

In [46]:
"Hello".upper()

'HELLO'

In [47]:
"This will split all words in a list".split()

['This', 'will', 'split', 'all', 'words', 'in', 'a', 'list']

# Python Program to Check where a String is Palindrome or not ?

In [46]:
myStr = "RaceCar"

#convert entire string to either lower or upper
myStr = myStr.lower() #racecar #sujit

#reverse string
revStr = reversed(myStr) #racecar #tijus


#check if the string is equal to its reverse
if list(myStr) == list(revStr):
    print("Given String is palindrome")
else:
    print("Given String is not palindrome")


Given String is not palindrome


In [ ]:
#write a  Python Program to Sort Words in Alphabetic Order?  H.W

# Python List

List is an ordered sequence of items. It is one of the most used datatype in Python and is very flexible. All the items in a list do not need to be of the same type.

In Python programming, a list is created by placing all the items (elements) inside square brackets [], separated by commas.

In [52]:
my_list = []

# list of integers
my_list = [1, 2, 3]

# list with mixed data types
my_list = [1, "Hello", 3.4]

In [54]:
print(my_list[1])

Hello


In [55]:
my_list[1] = 'Hi'
my_list

[1, 'Hi', 3.4]

# Python Tuple

Tuple is an ordered sequence of items same as list.The only difference is that tuples are immutable. Tuples once created cannot be modified.

In [56]:
# tuple with mixed datatypes
m_tuple = (1, "Hello", 3.4)
print(m_tuple)


(1, 'Hello', 3.4)


In [57]:
# nested tuple
m_tuple = ("machine Learning", [5, 4, 6], (1, 2, 3))
print(m_tuple)

('machine Learning', [5, 4, 6], (1, 2, 3))


In [20]:
#play tuple slicing, assigning variables, changing tuple and compare with lists  H.W

Some of the functions of Data Structures

# Lists

Data Structure:
    
A data structure is a collection of data elements (such as numbers or characters—or even other data structures) that is structured in some way, for example, by numbering the elements. The most basic data structure in Python is the "sequence".

-> List is one of the Sequence Data structure

-> Lists are collection of items (Strings, integers or even other lists)

-> Lists are enclosed in [ ]

-> Each item in the list has an assigned index value.

-> Each item in a list is separated by a comma

-> Lists are mutable, which means they can be changed.


# List Creation

In [58]:
emptyList = []

lst = ['one', 'two', 'three', 'four'] # list of strings

lst2 = [1, 2, 3, 4] #list of integers

lst3 = [[1, 2], [3, 4]] # list of lists

lst4 = [1, 'john', 24, 1.24] # list of different datatypes

print(lst4)


[1, 'john', 24, 1.24]


# List Length

In [4]:
lst = ['Machine Learning','Deep Learning','AI']
len(lst)

3

# List Append

In [5]:
lst = ['Machine Learning', 'Deep Learning', 'AI']

lst.append('Mathematics') # append will add the item at the end

print(lst)

['Machine Learning', 'Deep Learning', 'AI', 'Mathematics']


# List Insert

In [6]:
lst = ['Machine Learning', 'Deep Learning', 'AI']

lst.insert(2, "Mathematics") # will add element y at location x

print(lst)


['Machine Learning', 'Deep Learning', 'Mathematics', 'AI']


# List Remove

In [7]:
lst = ['Machine Learning', 'Deep Learning', 'AI', 'Mathematics']

lst.remove('Mathematics') #it will remove 'Mathematics' in a given list

print(lst)

['Machine Learning', 'Deep Learning', 'AI']


# List Append & Extend

In [8]:
lst = ['Machine Learning', 'Deep Learning', 'AI']

lst2 = ['Algebra', 'calculus']

#append 
lst.append(lst2)

print(lst)

['Machine Learning', 'Deep Learning', 'AI', ['Algebra', 'calculus']]


In [10]:
lst = ['Machine Learning', 'Deep Learning', 'AI']

lst.extend(lst2)

print(lst)

['Machine Learning', 'Deep Learning', 'AI', 'Algebra', 'calculus']


# List Delete

In [11]:
#del to remove item based on index position

lst = ['one', 'two', 'three', 'four', 'five']

del lst[1]
print(lst)

#or we can use pop() method
x = lst.pop(1)
print(x)

print(lst)

['one', 'three', 'four', 'five']
three
['one', 'four', 'five']


# List Sorting

The easiest way to sort a List is with the sorted(list) function. 

That takes a list and returns a new list with those elements in sorted order. 

The original list is not changed. 


In [12]:
#create a list with numbers
numbers = [3, 1, 6, 2, 8]

sorted_lst = sorted(numbers)


print("Sorted list :", sorted_lst)

#original list remain unchanged
print("Original list: ", numbers)

Sorted list : [1, 2, 3, 6, 8]
Original list:  [3, 1, 6, 2, 8]


In [14]:
lst = [15, 25,16, 5, 4.2]

#sort the list and stored in itself
lst.sort()
lst

[4.2, 5, 15, 16, 25]

# String Split to create a list

In [15]:
s = "Hello, Welcome to Machine Learning course"
split_lst = s.split() # default split is white-character: space or tab
print(split_lst)

['Hello,', 'Welcome', 'to', 'Machine', 'Learning', 'course']


# List extend using "+"

In [16]:
lst1 = ['Machine Learning', 'Deep Learning', 'AI']

lst2 = ['Algebra', 'calculus']

new_lst = lst1 + lst2

print(new_lst)


['Machine Learning', 'Deep Learning', 'AI', 'Algebra', 'calculus']


# List Count

In [59]:
numbers = [1, 2, 3, 1, 3, 4, 2, 5]

#frequency of 1 in a list
print(numbers.count(1))

#frequency of 3 in a list
print(numbers.count(5))

2
1


# List Looping

In [18]:
lst1 = ['Machine Learning', 'Deep Learning', 'AI']
for ele in lst1:
    print(ele)

Machine Learning
Deep Learning
AI


# List Comprehensions

List comprehensions provide a concise way to create lists. 

Common applications are to make new lists where each element is the result of some operations applied to each member of another sequence or iterable, or to create a subsequence of those elements that satisfy a certain condition.

In [60]:
# without list comprehension
cubes = []
for i in range(10):
    cubes.append(i**3) #list append
    print(cubes)
print(cubes)

[0]
[0, 1]
[0, 1, 8]
[0, 1, 8, 27]
[0, 1, 8, 27, 64]
[0, 1, 8, 27, 64, 125]
[0, 1, 8, 27, 64, 125, 216]
[0, 1, 8, 27, 64, 125, 216, 343]
[0, 1, 8, 27, 64, 125, 216, 343, 512]
[0, 1, 8, 27, 64, 125, 216, 343, 512, 729]
[0, 1, 8, 27, 64, 125, 216, 343, 512, 729]


In [20]:
#using list comprehension
cubes = [i**3 for i in range(10)]
print(cubes)

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729]


# Tuples

-> A tuple is similar to list

-> The diffence between the two is that we can't change the elements of tuple once it is assigned whereas in the list, elements can be changed

-> Indexing is possible in tuple

# Tuple Creation

In [21]:
#empty tuple
t = ()

#tuple having integers
t = (4, 2, 5)
print(t)

#tuple with mixed datatypes
t = (1, 'ML', 28, 'AI')
print(t)

#nested tuple
t = (1, (4, 2, 5), [1, 'ML', 28, 'AI'])
print(t)

(4, 2, 5)
(1, 'ML', 28, 'AI')
(1, (4, 2, 5), [1, 'ML', 28, 'AI'])


# Changing a Tuple

unlike lists, tuples are immutable

This means that elements of a tuple cannot be changed once it has been assigned. But, if the element is itself a mutable datatype like list, its nested items can be changed.

In [22]:
#creating tuple
t = (1, 2, 3, 4, [5, 6, 7])

t[2] = 'x' #will get TypeError

TypeError: 'tuple' object does not support item assignment

# Sets

-> A set is an unordered collection of items. Every element is unique (no duplicates).

-> The set itself is mutable. We can add or remove items from it.

-> Sets can be used to perform mathematical set operations like union, intersection, symmetric difference etc.

In [65]:
x = {10, 30, 20, 40, 5}
print(x)

# set cannot have duplicates
my_set = {1, 2, 3, 4, 3, 2}
my_set



{5, 40, 10, 20, 30}


{1, 2, 3, 4}

In [24]:
#Distinguish set and dictionary while creating empty set

# initializing set in multiple ways
x = {}

# check data type of x
print(type(x))

# initialize a with set()
y = set()

# check data type of x
print(type(y))

<class 'dict'>
<class 'set'>


In [105]:
# set cannot have mutable items
# here [9, 12] is a mutable list

my_set = {3, 6, [9, 12]}

my_set

TypeError: unhashable type: 'list'

In [50]:
#what if we try for indexing
my_set = {18,5,10,15}
my_set[0]


TypeError: 'set' object is not subscriptable

# Add element to a Set

In [68]:
my_set = {1, 5, 7, 8}
# add an element
my_set.add(2)
print(my_set)

# add multiple elements
my_set.update([2, 3, 4])
print(my_set)

{1, 2, 5, 7, 8}
{1, 2, 3, 4, 5, 7, 8}


# Remove elements from a Set

In [53]:
#items in a set can be removed by using following methods, 
#discard() and remove().

s = {1, 2, 3, 5, 4}
print(s)

s.discard(4)    #4 is removed from set s

print(s)

s.remove(3)
s

{1, 2, 3, 4, 5}
{1, 2, 3, 5}


{1, 2, 5}

# Python Set Operations

In [30]:
set1 = {1, 2, 3, 4, 5}
set2 = {3, 4, 5, 6, 7}

#union of 2 sets using | operator

print(set1 | set2)

#another way of getting union of 2 sets
print(set1.union(set2))

{1, 2, 3, 4, 5, 6, 7}
{1, 2, 3, 4, 5, 6, 7}


In [31]:
#intersection of 2 sets using & operator
print(set1 & set2)

#use intersection function 
print(set1.intersection(set2))

{3, 4, 5}
{3, 4, 5}


In [32]:
#set Difference: set of elements that are only in set1 but not in set2

print(set1 - set2)

#use differnce function 
print(set1.difference(set2))

{1, 2}
{1, 2}


# Dictionary

Python dictionary is an unordered collection of items. While other compound data types have only value as an element, a dictionary has a key: value pair.

# Dict Creation

In [74]:
#empty dictionary
my_dict = {}

#dictionary with integer keys
my_dict_1 = {1: 'ML', 2: 'AI'}
print(my_dict_1)

#dictionary with mixed keys
my_dict_2 = {'name': 'John', 1: ['abc', 'xyz']}
print(my_dict_2)


#create empty dictionary using dict()
my_dict_3 = dict()

my_dict_4 = dict([(1, 'abc'), (2, 'xyz')])    #create a dict with list of tuples
print(my_dict_4)

{1: 'ML', 2: 'AI'}
{'name': 'John', 1: ['abc', 'xyz']}
{1: 'abc', 2: 'xyz'}


In [70]:
my_dict = {'name': 'John', 'age': 35, 'address': 'America','education':'B.Tech'}

#get age
print(my_dict['age'])

#Another way
my_dict.get('age')

35


35

In [75]:
#update name

my_dict = {'name': 'John', 'age': 35, 'address': 'America','education':'M.Tech'}

my_dict['name'] = 'williams'

my_dict['education'] = 'Phd'

print(my_dict['name'])

my_dict['education']

williams


'Phd'

# Dictionary Methods

In [76]:
#fromkeys[seq[, v]] will return a new dictionary with keys from seq and value equal to v (defaults to None).
courses = {}.fromkeys(['Ml', 'AI', 'Deep Learning'], 0)
print(courses)

{'Ml': 0, 'AI': 0, 'Deep Learning': 0}


In [77]:
courses.keys()

dict_keys(['Ml', 'AI', 'Deep Learning'])

In [40]:
courses.values()

dict_values([0, 0, 0])

# Dict Comprehension

In [82]:
#Creating a new dictionary with only pairs where the value is larger than 2
d = {'a': 1, 'b': 2, 'c': 3, 'd': 4}
new_dict = {k:v for k, v in d.items() if v > 2}
print(new_dict)

{'c': 3, 'd': 4}


In [85]:
#We can also perform operations on the key value pairs
d = {'a':1,'b':2,'c':3,'d':4,'e':5}
d = {k + 'c':v * 2 for k, v in d.items() if v > 2}
print(d)

{'cc': 6, 'dc': 8, 'ec': 10}


# Numpy and its operations

It is a python library used for working with arrays

In [86]:
#install numpy with 'pip install numpy' comment
import numpy as np

#create an array

arr = np.array([3,6,9,12])
arr

array([ 3,  6,  9, 12])

# operations using NumPy

In [62]:
x = np.ones((4,3))# we can create ones  with required shape
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [87]:
y = np.ones(4)

new_arr = y + 1
new_arr

array([2., 2., 2., 2.])

In [88]:
#numpy for diagonal matrix

x = np.diag([3,6,9,12])
x

array([[ 3,  0,  0,  0],
       [ 0,  6,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 12]])

In [65]:
#comparisions
a = np.array([3, 6, 9, 12])

b = np.array([5, 2, 2, 4])

np.array_equal(a, b)

False

We can generate sin, log...etc functions using numpy 

In [89]:
x = np.arange(10)

np.log(x)

C:\Users\sb00747428\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in log
  This is separate from the ipykernel package so we can avoid doing imports until


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [90]:
np.sin(x)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [69]:
np.exp(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

Statistics

In [92]:
x = np.array([3,6,9,12])

y = np.array([5,10,15,20])

x.mean()
y.mean()

12.5

In [71]:
np.mean(x)

7.5

In [73]:
np.median(y)

12.5

In [74]:
np.std(y) #standard deviation

5.5901699437494745

# Shape Manipulation

In [93]:
#Flattening of arrays

x = np.array([[3, 6, 9], [5, 10, 15]])
x

array([[ 3,  6,  9],
       [ 5, 10, 15]])

In [94]:
x.ravel()

array([ 3,  6,  9,  5, 10, 15])

In [111]:
#Reshape again

x = x.reshape((2,3))
x  #output will be orginal array

array([[15, 10,  2],
       [ 6,  9,  3]])

In [113]:
#Insert a particular element

x[0,2] = 30

x 

array([[15, 10, 30],
       [ 6,  9, 30]])

In [104]:
#Resize an array
x = np.arange(8)
x.shape

(8,)

In [105]:
x.resize((12,))
x

array([0, 1, 2, 3, 4, 5, 6, 7, 0, 0, 0, 0])

In [108]:
#Transpose

x = np.ones((6,4))
x.shape

(6, 4)

In [109]:
x = x.T
x.shape

(4, 6)

# Data Sorting

In [110]:
#Sorting along an axis:
x = np.array([[15, 10, 2], [6, 9, 3]])
y = np.sort(x, axis=1)
y

array([[ 2, 10, 15],
       [ 3,  6,  9]])

# Arguments of a Function

In [114]:
def wish(name, msg):
    """
    Function to wish all students
    """
    print("Hello {0} , {1}".format(name, msg))

#call the function with arguments
wish("Students", "Good Evening")
wish('SR', 'HI' )


Hello Students , Good Evening
Hello SR , HI


#  Keyword Arguments

You should use **kwargs if you want to handle named arguments in a function

In [115]:
def wish(**kwargs):
    """
    Function to wish all students
    """
    if kwargs:
        print("Hello {0} , {1}".format(kwargs['name'], kwargs['msg']))
wish(name="Students", msg="Good Evening")


Hello Students , Good Evening


#  Arbitary Arguments

Sometimes, we do not know in advance the number of arguments that will be passed into a function.Python allows us to handle this kind of situation through function calls with arbitrary number of arguments.

In [116]:
def wish(*names):
    """
    This function wish all persons in the names tuple
    """
    print(names)
    
    for name in names:
        print("Hello,  {0} ".format(name))

wish("John", "williams", "abhinav")


('John', 'williams', 'abhinav')
Hello,  John 
Hello,  williams 
Hello,  abhinav 


# Recurison

A function can call other functions. It is even possible for the function to call itself. These type of construct are termed as recursive functions.

In [120]:
#Before going to program better to explain advantages and disadvantages and why we choose recursion

In [119]:
#program to print factorial of a number using recurion

def factorial(n):
    """
    recursive function to find the factorial of a given number
    """
    return 1 if n == 1 else (n * factorial(n-1))

n = 4

print ("Factorial of {0} is {1}".format(n, factorial(n)))


Factorial of 4 is 24


In [119]:
#try out more examples on recursion concept

# File handling

File is a named location on disk to store related information. It is used to permanently store data in a non-volatile memory.

When we want to read from or write to a file we need to open it first. When we are done, it needs to be closed, so that resources that are tied with the file are freed.

File operation:

1. Open a file

2. Read or write (perform operation)

3. Close the file

Python has a built-in function open() to open a file. This function returns a file object, also called a handle, as it is used to read or modify the file accordingly.

In [ ]:
#opening a file

f = open('filename.txt') #open file in current direcotry

#f = open('filename.txt',mode) syntax of open

# Python file modes

'r' Open a file for reading. (default)

'w' Open a file for writing. Creates a new file if it does not exist or truncates the file if it exists.

'x' Open a file for exclusive creation. If the file already exists, the operation fails.

'a' Open for appending at the end of the file without truncating it. Creates a new file if it does not exist.

't' Open in text mode. (default)

'b' Open in binary mode.

'+' Open a file for updating (reading and writing)

In [ ]:
f.close() #closes the opened file

f = open('filename.txt','r') #reads from a file

f = open('filename.txt','w') # writes in a file

In [121]:
#Example

f = open("example.txt", "w")
f.write("This is a File\n")
f.write("with no information\n")
f.close()
        

In [122]:
f = open("example.txt", "r")
f.read()

'This is a File\nwith no information\n'